import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      app_name: "Ludendorff",
      auth: {
        title: "Log-in to CLSU Property and Supplies Office",
        summary: "Enter your email address and password"
      },
      navigation: {
        manage: "Manage",
        account: "Account",
        assets: "Assets",
        inventories: "Inventory Reports",
        issued: "Issued Reports",
        stock_cards: "Stock Cards",
        audit_logs: "Audit Logs",
        users: "Users",
        categories: "Categories",
        profile: "Profile",
        settings: "Settings",
        reports: "Reports"
      },
      field: {
        email: "Email",
        password: "Password",
        current_password: "Current Password",
        confirm_password: "Confirm Password",
        first_name: "First Name",
        last_name: "Last Name",
        permissions: "Permissions",
        position: "Position",
        status: "Status",
        id: 'ID',
        name: 'Name',
        category: "Category",
        category_name: "Category Name",
        stock_number: "Stock Number",
        asset_description: "Description",
        unit_of_measure: "Unit of Measure",
        unit_value: "Unit Value",
        department_name: "Department Name",
        manager: "Manager",
        asset: "Asset",
        remarks: "Remarks",
        new_password: "New Password",
        submitted_date: "Submitted Date",
        search: "Search",
        rows_per_page: "Rows per page:",
        fund_cluster: "Fund Cluster",
        entity_name: "Entity Name",
        entity_position: "Entity Position",
        year_month: "Year Month",
        accountability_date: "Accountability Date",
        items: "Items",
        balance_per_card: "Balance Per Card",
        on_hand_count: "On Hand Count",
        serial_number: "Serial Number",
        unit_price: "Unit Price",
        entries: "Entries",
        article: "Article",
        quantity_issued: "Quantity Issued",
        unit_cost: "Unit Cost",
        responsibility_center: "Responsibility Center",
        date: "Date",
        reference: "Reference",
        received_quantity: "Received Quantity",
        requested_quantity: "Requested Quantity",
        issue_quantity: "Issue Quantity",
        issue_office: "Issue Office",
        balance_quantity: "Balance Quantity",
        balance_total_price: "Balance Total Price",
        stock_card: "Stock Card",
        item: "Item",
        reorder_point: "Reorder Point",
        supplier: "Supplier",
        not_set: "Not Set",
        total_value: "Total Value",
        amount: "Amount",
        unit: "Unit",
        receipt: "Receipt",
        requested: "Requested",
        issue: "Issue",
        balance: "Balance",
        quantity: "Quantity",
        office: "Office",
        total_price: "Total Price",
        days_to_consume: "No. of Days to Consume",
        ris_no: "RIS No.",
        value: "Value",
        filename: "Filename",
        subcategories: "Subcategories",
        subcategory: "Subcategory",
        subcategory_name: "Subcategory Name",
        entity: "Entity",
        total_issued_quantity: "Total Issued Quantity",
        recapitulation: "Recapitulation",
        total_cost: "Total Cost",
        uacs_object_code: "UACS Object Code",
        posted_by: "Posted by:",
        spreadsheet_file: "Spreadsheet file",
        worksheet_name: "Worksheet name",
        duplicate_items: "Duplicate Items",
        inventory_report_source: "Inventory Report Source",
        log_entry_id: "Log ID",
        data_type: "Data Type",
        identifier: "Identifier",
        data: "Data",
        before: "Before",
        after: "After",
        operation: "Operation",
        timestamp: "Timestamp"
      },
      alt: {
        clsu_logo: "The official logo of Central Luzon State University"
      },
      placeholder: {
        none: "None",
        stock_number: 'example: "OS–XXX–X1–000"',
        asset_description: 'example: "A4 Bond Paper"',
        classification: 'example: "Paper"',
        category: 'example: "Office Supplies"',
        unit_of_measure: 'example: "ream"',
        unit_value: 'example: "99.99"',
        remarks: 'example: "Common Supplies"',
        search: 'Type anything',
        entity_name: 'example: "John Doe"',
        entity_position: 'example: "Instructor II"',
        search_entries: "Search for entries"
      },
      permission: {
        read: "Read",
        write: "Write",
        delete: "Delete",
        audit: "Audit",
        manage_users: "Manage Users",
        administrative: "Administrative",
      },
      action: {
        update_avatar: "Update Avatar",
        change_name: "Change Name",
        change_password: "Change Password",
        request_reset: "Request Password Reset"
      },
      button: {
        cancel: "Cancel",
        ok: "Ok",
        continue: "Continue",
        add: "Add",
        save: "Save",
        previous: "Previous",
        next: "Next",
        close: "Close",
        delete: "Delete",
        disable: "Disable",
        enable: "Enable",
        export: "Export",
        dismiss: "Dismiss",
        duplicate: "Duplicate",
        show_menu: "Show menu",
        show_drawer: "Show drawer",
        sign_in: "Log in",
        sign_out: "Log out",
        go_to_home: "Go to Home",
        account_settings: "Account",
        request_asset: "Request Asset",
        create_asset: "Create Asset",
        create_user: "Create User",
        create_stock_card: "Create Stock Card",
        create_report: "Create Report",
        view_qr_code: "View QR Code",
        export_spreadsheet: "Export to Spreadsheet",
        download: "Download",
        filter: "Filter",
        back: "Back",
        set_quantity_source: "Set Quantity Source",
        import: "Import",
        choose_file: "Choose File",
        set_category: "Set Category",
        forgot_password: "Forgot Password?",
        send: "Send"
      },
      feedback: {
        error_generic: "An internal error occurred",
        authenticating: "Authenticating",
        saving: "Saving",
        empty_current_password: "You forgot to enter your current password",
        empty_new_password: "You forgot to enter your desired password",
        empty_confirm_password: "You forgot to enter the confirmation for your desired password",
        empty_category_name: "You forgot to enter the category name",
        empty_department_name: "You forgot to enter the department name",
        empty_asset_stock_number: "You forgot to enter the stock number",
        empty_asset_description: "You forgot to enter the description",
        empty_asset_type: "You forgot to select the category",
        empty_classification: "You forgot to enter the classification",
        empty_unit_of_measure: "You forgot to enter the unit of measure",
        empty_unit_value: "You forgot to enter the unit value",
        empty_asset_remarks: "You forgot to enter the remarks",
        empty_first_name: "You forgot to enter the first name",
        empty_last_name: "You forgot to enter the last name",
        empty_email_address: "You forgot to enter the email address",
        empty_position: "You forgot to enter a position",
        empty_balance_per_card: "You forgot to enter the balance per card",
        empty_on_hand_count: "You forgot to enter the on hand count",
        empty_fund_cluster: "You forgot to enter the fund cluster",
        empty_entity_name: "You forgot to enter the entity name",
        empty_entity_position: "You forgot to enter the entity position",
        empty_year_month: "You forgot to enter the year and month",
        empty_accountability_date: "You forgot to enter the accountability date",
        empty_quantity_issued: "You forgot to enter the quantity issued",
        empty_responsibility_center: "You forgot to enter the responsibility center",
        asset_created: "Asset created successfully",
        asset_updated: "Asset updated successfully",
        asset_removed: "Asset removed successfully",
        asset_imported: "Assets imported successfully",
        asset_saved: "Asset saved successfully",
        category_created: "Category created successfully",
        category_updated: "Category updated successfully",
        category_removed: "Category removed successfully",
        subcategory_removed: "Subcategory removed successfully",
        user_created: "User created successfully",
        user_updated: "User updated successfully",
        user_removed: "User removed successfully",
        inventory_created: "Inventory Report created successfully",
        inventory_updated: "Inventory Report updated successfully",
        inventory_removed: "Inventory Report removed successfully",
        issued_report_created: "Issued Report created successfully",
        issued_report_updated: "Issued Report updated successfully",
        issued_report_removed: "Issued report removed successfully",
        stock_card_created: "Stock Card created successfully",
        stock_card_updated: "Stock Card updated successfully",
        stock_card_removed: "Stock Card removed successfully",
        asset_create_error: "Error creating asset",
        asset_update_error: "Error updating asset",
        asset_remove_error: "Error removing asset",
        asset_import_error: "Error importing assets",
        category_create_error: "Error creating category",
        category_update_error: "Error updating category",
        category_remove_error: "Error removing category",
        user_create_error: "Error creating user",
        user_update_error: "Error updating user",
        user_remove_error: "Error removing user",
        inventory_create_error: "Error creating inventory report",
        inventory_update_error: "Error updating inventory report",
        inventory_remove_error: "Error removing inventory report",
        issued_report_create_error: "Error creating issued report",
        issued_report_update_error: "Error updating issued report",
        issued_report_remove_error: "Error removing issued report",
        stock_card_create_error: "Error creating stock card",
        stock_card_update_error: "Error updating stock card",
        stock_card_remove_error: "Error removing stock card",
        reset_link_sent: "Password reset link sent",
        empty_copies: "Number of copies cannot be empty",
        name_changed: "Name changed successfully",
        password_changed: "Password changed successfully",
        avatar_changed: "Profile Picture changed successfully",
        name_change_error: "Error updating name",
        password_change_error: "Error updating password",
        avatar_change_error: "Error updating user profile picture",
        stock_number_already_exists: "The stock number you entered already exists",
        subcategory_already_exists: "Subcategory already exists",
        duplicate_items_exists: "Duplicate items still exists",
        cost_cannot_zero: "Item price or cost cannot be zero"
      },
      error: {
        no_permissions_header: "Insufficient Permissions",
        no_permissions_summary_read: "The page you are trying to reach is restricted. Contact the system administrator for assistance.",
        no_permissions_summary_write: "Unfortunately, you do not have the proper permissions to perform this operation. Contact the system administrators for assistance.",
        not_found_header: "Whoops!",
        not_found_summary: "We can't seem to find that page you're looking for.",
        not_found_info: "Maybe you can head back home and find it there instead?",
      },
      info: {
        user_status_normal: "Normal",
        user_status_disabled: "Disabled",
        user_editor_admin_permission: "Adding \"Administrative\" permission overrides lower permission rules.",
        category_count_not_zero: "There are assets with this category",
        department_count_not_zero: "There are users who are in this department",
        native_app_available: "You are currently using Ludendorff in a mobile environment; consider installing the native app to access more features of the system.",
        stock_number_cannot_be_changed: "The Asset's stock number cannot be changed once entered",
        stock_number_exists: "This stock number already exists in the database, if you don't change it, the current one will be replaced by this one.",
        import_requirements_asset_spreadsheet: "Ludendorff requires the spreadsheet file to contain a total of seven (7) columns with the exact order of data as the following: (Stock Number, Description, Category, Subcategory, Unit of Measure, Unit Value and Remarks (optional))."
      },
      settings: {
        dark_theme: "Dark Theme",
        dark_theme_summary: "Make the interface darker and easier on the eyes.",
        override_individual_density: "Override Individual Component Density",
        override_individual_density_summary: "Use the global setting for table row density instead of their individual setting",
        table_row_density: "Table Row Density",
        table_row_density_summary: "Customize the size of the row paddings in the data table.",
        table_row_density_compact: "Compact",
        table_row_density_standard: "Standard",
        table_row_density_comfortable: "Comfortable",
        configure_entity: "Configure Entity",
        configure_entity_summary: "Modify and update the entity data used in the Inventory and Issued Item Reports."
      },
      dialog: {
        sign_out: "Log out?",
        sign_out_summary: "Are you sure you want to end your session? You will need to enter your credentials again next time.",
        asset_remove: "Remove asset?",
        asset_remove_summary: "Do you want to remove this asset? Once finished, this action cannot be undone.",
        category_remove: "Remove category?",
        category_remove_summary: "Do you want to remove this category? Once finished, this action cannot be undone.",
        user_disable_title: "Disable this user account?",
        user_disable_summary: "Are you sure you want to disable this user account? With proper permissions, you can always enable this account in the future.",
        user_enable_title: "Enable this user account?",
        user_enable_summary: "Are you sure you want to enable this user account? With proper permissions, you can always disable this account in the future.",
        user_remove: "Remove this user?",
        user_remove_summary: "Are you sure you want to remove this user account? All data associated with this account will be removed as well and cannot be recovered.",
        issued_report_remove: "Remove Report?",
        issued_report_remove_summary: "Are you sure you want to remove this report? Once finished, this action cannot be undone.",
        stock_card_remove: "Remove Stock Card?",
        stock_card_remove_summary: "Are you are you want to remove this stock card? Once finished, this action cannot be undone.",
        inventory_remove: "Remove Report?",
        inventory_remove_summary: "Are you sure you want to remove this report? Once finished, this action cannot be undone.",
        send_reset_link_title: "Send Password Reset Link",
        send_reset_link_message: "If you forgot your password for this account, you can request to reset it requesting a reset email.",
        duplicate_title: "Duplicate Record",
        duplicate_summary: "You can create duplicated copy of the records in the database, to avoid manual input.",
        category_create: "Create New Category",
        category_update: "Update Existing Category",
        subcategory_create: "Create New Subcategory",
        subcategory_update: "Update Existing Subcategory",
        asset_create: "Create New Asset",
        asset_update: "Update Existing Asset",
        user_create: "Create New User",
        user_update: "Update Existing User",
        inventory_create: "Create New Report",
        inventory_update: "Update Existing Report",
        inventory_item_create: "Create New Item",
        inventory_item_update: "Update Existing Item",
        issued_create: "Create New Report",
        issued_update: "Update Existing Report",
        issued_item_create: "Create New Item",
        issued_item_update: "Update Existing Item",
        stock_card_create: "Create New Stock Card",
        stock_card_update: "Update Existing Stock Card",
        stock_card_entry_create: "Create New Entry",
        stock_card_entry_update: "Update Existing Entry",
        audit_log_view: "View Log",
        entity_update: "Update Entity",
        select_category: "Select Category",
        select_asset: "Select Asset",
        select_user: "Select User",
        select_issued_report: "Select Issued Report",
        select_inventory_report: "Select Inventory Report",
        import_assets: "Import Assets",
        view_qr_code: "View QR-Code",
        view_qr_code_summary: "To save the code, right-click the image then select \"Save Image\".",
        view_inventory_report: "View Inventory Report",
        finish_account_setup: "Finish Account Setup",
        finish_account_setup_summary: "To finish your account setup, enter a new password to replace the default one generated by the system.",
        export_spreadsheet: "Export Spreadsheet",
        export_spreadsheet_summary: "Configure filename and worksheet name before exporting the data to the spreadsheet format.",
        issued_is_more_than_current: "Not Enough Quantity",
        issued_is_more_than_current_summary: "The requested issued quantity for the specified asset is more than what is specified in the quantity in the source inventory report.",
        stock_number_not_found_on_report: "Stock Number not Found",
        stock_number_not_found_on_report_summary: "The requested stock number is not found on the specified inventory report. Select another one then try again.",
        reset_email_sent: "Check your email",
        reset_email_sent_summary: "An email has been sent to your email address. Follow the directions in the email to reset your password.",
        duplicate_asset_items: "Duplicate Items",
        duplicate_asset_items_summary: "There are duplicate items found on the data read from the selected spreadsheet file. Resolve these conflicts first to continue.",
        data_missing: "Some data are missing",
        data_missing_summary: "There are some fields or entries that have missing values. Are you sure you want to proceed saving this record?",
        audit_log_remove: "Remove log entry?",
        audit_log_remove_summary: "This will permanently remove this log entry from the system and cannot be recovered later. Are you sure you want to remove this log entry?"
      },
      template: {
        full_name: "{{first}} {{last}}",
        count: "Count: {{count}}",
        as_of_year_month: "As of {{yearMonth}}",
        inventory_entity: "For which, {{name}}, {{position}}, Central Luzon State University, is accountable, having assumed such accountability on {{date}}",
        subcategories_include: "Subcategories include: {{includes}}",
        subcategories_include_over_10: "Subcategories include: {{includes}} and {{count}} more others",
        entity: "{{name}}, ({{position}})",
        audit_log_operation_data: "{{operation}}-{{type}} with ID: {{id}}"
      },
      empty: {
        asset_header: "No Assets Added",
        asset_summary: "There are no assets available.",
        asset_import_header: "No Data Available",
        asset_import_summary: "Once the data from the spreadsheet is available to be imported, they will show up here.",
        category_header: "No Categories Added",
        category_summary: "There are no categories available that can be used to organize the assets.",
        user_header: "No Users Added",
        user_summary: "There are no users available.",
        search_header: "No Results",
        search_summary: "There are no items matched on your query \"{{query}}\"",
        inventory_header: "No Inventory Reports Available",
        inventory_summary: "There are no Physical Count of Inventories Reports that are available on the database.",
        stock_card_header: "No Stock Cards Added",
        stock_card_summary: "There are no Stock Cards that are available on the database.",
        issued_reports_header: "No Issued Items Reports Available",
        issued_reports_summary: "There are no Supplies and Materials Issued Reports that are available on the database.",
        subcategories: "No subcategories added",
        no_duplicates_header: "No Duplicates Detected",
        no_duplicates_summary: "There are no duplicate records detected",
        audit_logs_header: "No Logs Recorded",
        audit_logs_summary: "There have been no recorded logs yet, or they may have been removed.",
        no_before_data: "Data doesn't exist before",
        no_after_data: "Data have been deleted"
      },
      types: {
        asset: "Asset",
        inventory: "Inventory Report",
        issued: "Issued Report",
        stockCard: "Stock Card",
        user: "User Data"
      },
      operation: {
        create: "Create",
        update: "Modify",
        remove: "Remove"
      },
      document: {
        stock_card: "Stock Card",
        inventory: "Report on the Physical Count of Inventories",
        issued: "Report of Supplies and Materials Issued",
        type_of_inventory_item: "Type of Inventory Item",
      },
      unknown: "Unknown",
      information: "Information",
      actions: "Actions",
    }
  }
}

i18n.use(initReactI18next)
  .init({
    resources,
    lng: "en",
    interpolation: {
      escapeValue: false
    }
  }).then(() => {
});

export default i18n;
const t = i18n.t.bind(i18n);
export { t };